---
ID: "61abb421-7323-4050-82c2-cb31540e4c9a"
Parent: "29b5f2ed-6d82-49f5-b4b7-4e89a39c8d8a"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Verticals/Services/Presentation/Headless Variants/Promo CTA/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f227900f-eb89-4817-a582-f2f6531b21e5"
