---
ID: "1d0ff4c5-5f07-4666-9061-0210d0692984"
Parent: "90d315e8-aa42-4b23-a7eb-4491396453f8"
Template: "90d315e8-aa42-4b23-a7eb-4491396453f8"
Path: /sitecore/templates/Project/Verticals/Components/Hero/__Standard Values
SharedFields:
- ID: "3ed91913-9018-4580-a112-9cb5b921fcca"
  Hint: Image
  Value: |
    <image mediaid="{7ED35C53-B0C3-4508-8561-EDEC520BB63A}" alt="top-view-passport-money-with-copy-space" height="" width="" hspace="" vspace="" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "098585dd-31d0-4f64-aed2-9deaef046038"
    - ID: "8ff063ab-c9f1-4628-a0b1-2afb5e7f5560"
      Hint: Link
      Value: |
        <link text="Details" linktype="external" url="https://example.com" anchor="" target="" />
    - ID: "a3cbbb91-442e-441c-a6e2-5896c19d8711"
      Hint: Text
      Value: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</p>
    - ID: "f44602f9-172c-4987-aaf6-1fb2ab0f75a1"
      Hint: Title
      Value: Lorem ipsum dolor sit amet
