---
ID: "f76d0e6e-24fa-4fa8-8e3a-b594354db2c3"
Parent: "9630299a-f0c0-4b95-bb56-adb394885d48"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Verticals/Services
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c53e045d-4afb-43ea-be9a-aaf1d6c1cdad"
