---
ID: "2532e94e-42ed-41fc-9d31-b48e33cd876c"
Parent: "66aff2d9-d6ba-4c10-a049-9b4047c29fc8"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Verticals/Services/Presentation/Headless Variants/Author List/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f2dfa2d9-e211-4fc6-b766-a8ca5b0d3a0c"
