---
ID: "5976cd6a-9c09-428b-ae34-83de5144c859"
Parent: "96e6c089-71db-4cb0-942e-07a170da7187"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Verticals/Services/Presentation/Headless Variants/CTA Banner/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5658e620-4061-4964-9e0c-5f777dcb4a91"
